/**
 * Cross-linking map for resource pages.
 *
 * Each key is a resource slug; its value is the ordered list of related
 * resource slugs that should appear in the "Related Guides" section at the
 * bottom of that page.
 *
 * Source of truth: the live shadow.inc site as of 2026-04-14.
 */
export const resourceCrosslinks: Record<string, string[]> = {
  "ai-content-pitch-generation-agencies": [
    "pr-operating-system",
    "thought-leadership-strategy",
    "client-intelligence-ai-memory-pr",
  ],
  "ai-search-visibility-pr": [
    "pr-operating-system",
    "share-of-voice-pr",
    "media-monitoring-pr-agencies",
    "generative-engine-optimization",
    "answer-engine-optimization",
  ],
  "share-of-voice-pr": [
    "pr-operating-system",
    "media-monitoring-pr-agencies",
    "ai-search-visibility-pr",
    "pr-reporting-measurement",
    "the-measurement-trap",
    "the-data-layer",
  ],
  "pr-reporting-measurement": [
    "pr-operating-system",
    "share-of-voice-pr",
    "pr-operating-system-roi",
    "the-measurement-trap",
    "improve-agency-margins-ai",
  ],
  "media-monitoring-pr-agencies": [
    "pr-operating-system",
    "share-of-voice-pr",
    "ai-search-visibility-pr",
    "competitive-intelligence-pr-agencies",
    "best-ai-tools-pr-agencies",
  ],
  "thought-leadership-strategy": [
    "pr-operating-system",
    "ai-content-pitch-generation-agencies",
    "ai-search-visibility-pr",
    "pr-strategy",
  ],
  "competitive-intelligence-pr-agencies": [
    "pr-operating-system",
    "media-monitoring-pr-agencies",
    "share-of-voice-pr",
    "the-data-layer",
    "pr-strategy",
  ],
  "ai-media-lists-pr-agencies": [
    "pr-operating-system",
    "best-pr-platforms-agencies",
    "competitive-intelligence-pr-agencies",
    "best-ai-tools-pr-agencies",
  ],
  "client-intelligence-ai-memory-pr": [
    "pr-operating-system",
    "ai-workflow-automation-pr-agencies",
    "pr-operating-system-roi",
    "the-data-layer",
    "what-is-shadow",
  ],
  "ai-workflow-automation-pr-agencies": [
    "pr-operating-system",
    "client-intelligence-ai-memory-pr",
    "pr-operating-system-roi",
    "ai-agents-for-business",
    "what-ai-actually-changes",
  ],
  "pr-operating-system-roi": [
    "pr-operating-system",
    "shadow-vs-pr-tool-stack",
    "ai-workflow-automation-pr-agencies",
    "improve-agency-margins-ai",
    "resources-scale-agency-without-headcount",
  ],
  "shadow-vs-pr-tool-stack": [
    "pr-operating-system",
    "best-pr-platforms-agencies",
    "pr-operating-system-roi",
    "replace-agency-tech-stack",
    "improve-agency-margins-ai",
  ],
  "best-pr-platforms-agencies": [
    "pr-operating-system",
    "shadow-vs-pr-tool-stack",
    "pr-operating-system-roi",
    "best-ai-tools-pr-agencies",
    "what-is-shadow",
  ],
  "pr-operating-system": [
    "best-pr-platforms-agencies",
    "shadow-vs-pr-tool-stack",
    "pr-operating-system-roi",
    "ai-workflow-automation-pr-agencies",
    "client-intelligence-ai-memory-pr",
    "what-is-shadow",
    "what-is-agency-infrastructure",
  ],
  "the-data-layer": [
    "best-ai-tools-pr-agencies",
    "communications-technology",
    "what-is-shadow",
  ],
  "what-comes-next": [
    "resources-scale-agency-without-headcount",
    "what-is-shadow",
    "what-is-agency-infrastructure",
  ],
  "what-ai-actually-changes": [
    "best-ai-tools-pr-agencies",
    "what-is-shadow",
  ],
  "the-business-model-crisis": [
    "resources-scale-agency-without-headcount",
    "improve-agency-margins-ai",
    "what-is-shadow",
  ],
  "the-measurement-trap": [
    "pr-strategy",
    "improve-agency-margins-ai",
    "what-is-agency-infrastructure",
    "what-is-shadow",
  ],
  "the-attention-shift": [
    "pr-strategy",
    "communications-technology",
    "generative-engine-optimization",
    "what-is-shadow",
  ],
  "the-trust-shift": [
    "pr-strategy",
    "what-is-shadow",
  ],
  "services-as-software": [
    "pr-operating-system",
    "ai-workflow-automation-pr-agencies",
    "pr-operating-system-roi",
    "client-intelligence-ai-memory-pr",
    "the-business-model-crisis",
    "what-is-shadow",
  ],
  "replace-agency-tech-stack": [
    "pr-operating-system",
    "shadow-vs-pr-tool-stack",
    "pr-operating-system-roi",
    "improve-agency-margins-ai",
    "resources-scale-agency-without-headcount",
    "best-ai-tools-pr-agencies",
    "what-is-shadow",
  ],
  "improve-agency-margins-ai": [
    "pr-operating-system",
    "pr-operating-system-roi",
    "shadow-vs-pr-tool-stack",
    "ai-workflow-automation-pr-agencies",
    "resources-scale-agency-without-headcount",
    "best-ai-tools-pr-agencies",
    "what-is-shadow",
  ],
  "resources-scale-agency-without-headcount": [
    "what-is-agency-infrastructure",
    "best-ai-tools-pr-agencies",
    "improve-agency-margins-ai",
    "replace-agency-tech-stack",
    "what-is-shadow",
  ],
  "best-ai-tools-pr-agencies": [
    "what-is-agency-infrastructure",
    "resources-scale-agency-without-headcount",
    "improve-agency-margins-ai",
    "replace-agency-tech-stack",
    "what-is-shadow",
  ],
  "what-is-agency-infrastructure": [
    "pr-operating-system",
    "what-is-shadow",
    "best-pr-platforms-agencies",
    "shadow-vs-pr-tool-stack",
    "ai-workflow-automation-pr-agencies",
    "client-intelligence-ai-memory-pr",
  ],
  "generative-engine-optimization": [
    "ai-search-visibility-pr",
    "answer-engine-optimization",
    "share-of-voice-pr",
    "media-monitoring-pr-agencies",
    "pr-operating-system",
    "ai-agents-for-business",
  ],
  "answer-engine-optimization": [
    "generative-engine-optimization",
    "ai-search-visibility-pr",
    "share-of-voice-pr",
    "pr-reporting-measurement",
    "pr-operating-system",
  ],
  "ai-agents-for-business": [
    "pr-operating-system",
    "ai-workflow-automation-pr-agencies",
    "client-intelligence-ai-memory-pr",
    "what-is-shadow",
    "services-as-software",
    "best-pr-platforms-agencies",
  ],
  "pr-strategy": [
    "pr-operating-system",
    "competitive-intelligence-pr-agencies",
    "pr-reporting-measurement",
    "thought-leadership-strategy",
    "media-monitoring-pr-agencies",
    "ai-search-visibility-pr",
  ],
  "communications-technology": [
    "pr-strategy",
    "what-is-shadow",
  ],
  "what-is-shadow": [
    "pr-operating-system",
    "best-pr-platforms-agencies",
    "shadow-vs-pr-tool-stack",
    "pr-operating-system-roi",
    "ai-workflow-automation-pr-agencies",
    "client-intelligence-ai-memory-pr",
    "what-is-agency-infrastructure",
  ],
};
