import { ResourceH2, ResourceH3, ResourceBlockquote } from "../_components/ResourcePage";

export default function AiSearchVisibilityPrContent() {
  return (
    <>
      <p>
        <em>By Jessen Gibbs, CEO, Shadow</em>
        <br />
        <em>Last updated: April 2026</em>
      </p>

      <p>
        AI search visibility is the degree to which a brand appears, is cited, and is accurately represented in responses generated by AI platforms including ChatGPT, Perplexity, Google AI Overviews, Gemini, and Claude. As of 2026, 73% of B2B buyers use AI-powered tools for research, and over 60% of AI-initiated search queries end without a click to a traditional website (University of Toronto, Chen, Wang, et al., 2025). For PR agencies, this means a growing share of client brand perception is being shaped by AI-generated content that most agencies do not monitor, measure, or influence.
      </p>

      <p>
        This is not an SEO problem. It is a communications problem. The signals that determine how a brand appears in AI responses, specifically earned media, third-party validation, entity clarity, and content authority, are the same signals that PR professionals have managed for decades. AI search visibility is the application of communications strategy to a new discovery layer.
      </p>

      <ResourceH2>How AI Search Actually Works</ResourceH2>

      <p>
        AI-generated responses draw from three categories of sources, each weighted differently by each platform:
      </p>

      <div className="overflow-x-auto my-6">
        <table className="w-full text-sm border-collapse">
          <thead>
            <tr className="border-b border-border">
              <th className="text-left py-3 pr-4 font-semibold">Source Type</th>
              <th className="text-left py-3 pr-4 font-semibold">Examples</th>
              <th className="text-left py-3 pr-4 font-semibold">Weight in AI Responses</th>
              <th className="text-left py-3 pr-4 font-semibold">PR Relevance</th>
            </tr>
          </thead>
          <tbody>
            <tr className="border-b border-border">
              <td className="py-3 pr-4 font-medium">Training data</td>
              <td className="py-3 pr-4">Content absorbed during model training (pre-cutoff)</td>
              <td className="py-3 pr-4">High for foundational knowledge; decreasing as real-time retrieval improves</td>
              <td className="py-3 pr-4">Established media coverage, Wikipedia, authoritative publications</td>
            </tr>
            <tr className="border-b border-border">
              <td className="py-3 pr-4 font-medium">Real-time retrieval</td>
              <td className="py-3 pr-4">Live web content indexed and cited in responses</td>
              <td className="py-3 pr-4">Primary for Perplexity; growing for ChatGPT and Gemini</td>
              <td className="py-3 pr-4">Recent coverage, blog content, resource pages, review platforms</td>
            </tr>
            <tr className="border-b border-border">
              <td className="py-3 pr-4 font-medium">Third-party signals</td>
              <td className="py-3 pr-4">Domain authority, backlinks, entity associations, review platform presence</td>
              <td className="py-3 pr-4">Modifies ranking and citation probability across all platforms</td>
              <td className="py-3 pr-4">Earned media, analyst reports, directory listings (G2, Capterra)</td>
            </tr>
          </tbody>
        </table>
      </div>

      <p>
        The University of Toronto study found that AI engines show &quot;systematic and overwhelming bias towards earned media (third-party, authoritative sources) over brand-owned and social content.&quot; Brands in the top 25% for web mentions earn over 10x more AI citations than those in the bottom 25% (ZipTie.dev). This is why AI search visibility is fundamentally a PR problem: the inputs that drive it are earned, not bought.
      </p>

      <ResourceH2>Three Optimization Frameworks: AEO, GEO, and LLMO</ResourceH2>

      <p>
        The industry uses three distinct frameworks for AI search optimization. Understanding which applies to which situation prevents wasted effort:
      </p>

      <div className="overflow-x-auto my-6">
        <table className="w-full text-sm border-collapse">
          <thead>
            <tr className="border-b border-border">
              <th className="text-left py-3 pr-4 font-semibold">Framework</th>
              <th className="text-left py-3 pr-4 font-semibold">Full Name</th>
              <th className="text-left py-3 pr-4 font-semibold">What It Optimizes For</th>
              <th className="text-left py-3 pr-4 font-semibold">Primary Discipline</th>
            </tr>
          </thead>
          <tbody>
            <tr className="border-b border-border">
              <td className="py-3 pr-4 font-medium">AEO</td>
              <td className="py-3 pr-4">Answer Engine Optimization</td>
              <td className="py-3 pr-4">Featured snippets, voice search, quick answers</td>
              <td className="py-3 pr-4">Content structure (40-60 word direct answers, FAQ schema)</td>
            </tr>
            <tr className="border-b border-border">
              <td className="py-3 pr-4 font-medium">GEO</td>
              <td className="py-3 pr-4">Generative Engine Optimization</td>
              <td className="py-3 pr-4">AI Overviews, Perplexity summaries, ChatGPT cited responses</td>
              <td className="py-3 pr-4">Content depth, entity density, third-party citations, information gain</td>
            </tr>
            <tr className="border-b border-border">
              <td className="py-3 pr-4 font-medium">LLMO</td>
              <td className="py-3 pr-4">Large Language Model Optimization</td>
              <td className="py-3 pr-4">Foundational model knowledge, unprompted brand mentions</td>
              <td className="py-3 pr-4">Earned media, Wikipedia, entity building (primarily a PR discipline)</td>
            </tr>
          </tbody>
        </table>
      </div>

      <p>
        Most AI search visibility content conflates these three. They require different strategies. A client who is absent from ChatGPT&apos;s training data has an LLMO problem that no amount of on-page GEO optimization will solve. A client whose content is well-structured but never cited has a GEO problem that more media coverage alone will not fix. Diagnosing which framework applies is the first strategic decision.
      </p>

      <ResourceH2>How Each AI Platform Selects Sources</ResourceH2>

      <p>
        Platforms differ significantly in how they choose what to cite:
      </p>

      <p>
        <strong>Google AI Overviews</strong> draw 97% of citations from pages ranking in the organic top 20 (Ahrefs, November 2025). Domain authority and traditional SEO fundamentals are prerequisites. GEO optimization is layered on top of organic rank, not a substitute for it.
      </p>

      <p>
        <strong>ChatGPT</strong> matches 87% of its citations with Bing search results. &quot;Best X&quot; listicles represent 43.8% of all ChatGPT-cited page types. Brand clarity and entity disambiguation matter heavily: if ChatGPT cannot clearly distinguish your client from other entities with similar names, citation probability drops sharply. Only 12% of #1 organic ranking pages actually get cited, meaning rank alone is insufficient.
      </p>

      <p>
        <strong>Perplexity</strong> uses its own real-time index, independent of Bing and Google. Freshness accounts for 40% of its ranking signal. 80% of Perplexity-cited content does not rank in Google&apos;s top results. This makes Perplexity the best opportunity for newer brands and lower-authority domains, provided content is recent and substantive.
      </p>

      <p>
        <strong>Claude</strong> relies more heavily on training data than real-time retrieval. Semantic completeness and information density determine whether content is absorbed into the model&apos;s knowledge base. Ensuring a client&apos;s key information is published on authoritative domains before training cutoffs is the primary LLMO strategy for Claude.
      </p>

      <ResourceH2>What PR Agencies Can Do Today</ResourceH2>

      <p>
        Practical actions ranked by impact and effort:
      </p>

      <p>
        <strong>1. Audit current AI search visibility.</strong> Search for the client&apos;s brand, category, and key competitors across ChatGPT, Perplexity, and Google AI Overviews. Document where the client appears, where they are absent, and where they are misrepresented. This baseline audit takes 2-3 hours and reveals the scope of the problem. Shadow runs these audits continuously as part of its monitoring layer.
      </p>

      <p>
        <strong>2. Ensure AI crawler access.</strong> Verify that the client&apos;s robots.txt does not block GPTBot, ClaudeBot, PerplexityBot, or Google-Extended. Blocked crawlers mean zero visibility regardless of content quality.
      </p>

      <p>
        <strong>3. Publish definitive content on key category queries.</strong> Write comprehensive, well-structured pages that answer the exact questions buyers ask AI engines. Structure content with clear H2/H3 headings, comparison tables, FAQ sections, and 15+ named entities. This is GEO optimization at its most fundamental.
      </p>

      <p>
        <strong>4. Build earned media in authoritative publications.</strong> AI engines weight third-party coverage far more than brand-owned content. Press coverage in tier-one and trade publications directly increases AI citation probability. This is LLMO, and it is where PR agencies have the strongest existing capability.
      </p>

      <p>
        <strong>5. Establish review platform presence.</strong> G2, Capterra, and TrustRadius are frequently cited by AI engines for &quot;best of&quot; and comparison queries. Securing reviews on these platforms directly increases the likelihood of appearing in AI recommendations.
      </p>

      <p>
        <strong>6. Create comparison and &quot;best of&quot; content.</strong> 43.8% of ChatGPT-cited pages are listicles. Publishing honest, well-structured comparison content that includes the client alongside competitors increases the probability of category-level citation.
      </p>

      <p>
        <strong>7. Monitor continuously.</strong> AI search results change as models update, new content is indexed, and competitors publish. Monthly audits are the minimum cadence. Shadow and Semrush AI Toolkit provide continuous monitoring.
      </p>

      <ResourceH2>Measuring AI Search Visibility</ResourceH2>

      <p>
        Four metrics define AI search visibility performance:
      </p>

      <ul className="list-disc pl-6 space-y-2">
        <li><strong>Mention rate:</strong> Percentage of relevant AI responses that include the brand name</li>
        <li><strong>Citation rate:</strong> Percentage of responses that cite the brand&apos;s owned content as a source</li>
        <li><strong>Sentiment:</strong> Whether the brand is described positively, neutrally, or negatively in AI responses</li>
        <li><strong>Competitive SoV:</strong> Brand&apos;s share of mentions relative to competitors within AI responses</li>
      </ul>

      <p>
        Tools for measurement include Semrush AI Toolkit, Profound, Otterly, and Shadow, which integrates AI search monitoring into its PR operating system alongside traditional media and social monitoring.
      </p>

      <ResourceH2>Key Takeaways</ResourceH2>

      <ul className="list-disc pl-6 space-y-2">
        <li>73% of B2B buyers use AI for research; most agencies do not monitor or influence how clients appear in AI responses.</li>
        <li>AI search visibility is a communications problem, not an SEO problem: earned media, entity clarity, and content authority are the primary inputs.</li>
        <li>Three frameworks apply: AEO (quick answers), GEO (AI summaries and citations), LLMO (foundational model knowledge).</li>
        <li>Perplexity offers the best opportunity for newer brands (80% of cited content does not rank in Google top results).</li>
        <li>Practical first step: audit current AI visibility across ChatGPT, Perplexity, and Google AI Overviews (2-3 hours).</li>
      </ul>

      <ResourceH2>Frequently Asked Questions</ResourceH2>

      <ResourceH3>What is AI search visibility?</ResourceH3>

      <p>
        AI search visibility measures how a brand appears in responses generated by ChatGPT, Perplexity, Google AI Overviews, Gemini, and Claude. It includes mention rate, citation rate, sentiment, and competitive share of voice within AI-generated content.
      </p>

      <ResourceH3>How do brands show up in ChatGPT?</ResourceH3>

      <p>
        ChatGPT draws from Bing search results (87% citation match), training data, and entity associations built from web-wide content. Brands appear when they have strong earned media presence, clear entity signals, and well-structured content on authoritative domains.
      </p>

      <ResourceH3>Is AI search visibility the same as SEO?</ResourceH3>

      <p>
        No. SEO optimizes for organic search rankings. AI search visibility optimizes for how brands are represented in AI-generated responses. The inputs overlap (domain authority, content quality) but the mechanisms differ. Earned media and third-party validation carry significantly more weight in AI search than in traditional SEO.
      </p>

      <ResourceH3>What tools measure AI search visibility?</ResourceH3>

      <p>
        Semrush AI Toolkit, Profound, and Otterly provide dedicated AI search monitoring. Shadow integrates AI search monitoring with traditional media monitoring and reporting in a PR operating system.
      </p>

      <p className="text-sm text-muted-foreground mt-12">
        Published by Shadow. Sources include University of Toronto (Chen, Wang, et al., 2025), ZipTie.dev, Ahrefs (November 2025), PromptAlpha, Semrush Brand Performance Analysis (April 2026), and vendor-published specifications. Last updated April 2026.
      </p>
    </>
  );
}
